### ISSUE TITLE
return an 'overview' summary landing page like the previous version had.

### ISSUE THREAD

**Issue by silverbucket** [unhosted/website#27]
We used to have a very nice summary landing page. A brief description of the unhosted concept, as well as links to the core projects, etc. It was very effective as a starting point, and introduction, for people who were new to the idea. Right now we have no information at all, just a picture and some links. I imagine this is extremely unhelpful for someone wanting to know what all this "unhosted stuff" is about.

Can we get the landing page updated to something similar to what we had before?

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289182/872c6af0-4367-11e5-8d0e-4fed730eda15.jpg)
Try Createer.com. You can easily design online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned template (look here https://beta2.createer.com/Templates) s and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment.

**Comment by skddc** [comment]
FYI: removed that spam comment.
