### ISSUE TITLE
How can I add an app to the list?

### ISSUE THREAD

**Issue by Thatoo** [unhosted/website#60]
Hello,

How can I add to the list this app, Cesium, https://github.com/duniter/cesium , a web client for Duniter (https://github.com/duniter/duniter)?

Thank you,

Thatoo

**Comment by Thatoo** [comment]
I have made a pull request for it now.

**Comment by Thatoo** [comment]
I have done the change required...

**Comment by michielbdejong** [comment]
Sorry, commented on your PR now. Just running out of the coworking space now - I'll merge it when I get home.

**Comment by michielbdejong** [comment]
Done, thanks!
