### ISSUE TITLE
`add yours` link point to this repo

### ISSUE THREAD

**Issue by lduboeuf** [unhosted/website#62]
hello,
i would like to add an app to unhosted but when clicking to `add yours` in (https://unhosted.org/apps/) it points to this repository. Is it a normal behavior ?

**Comment by skddc** [comment]
Yes, I think the idea is that you edit https://github.com/unhosted/website/blob/master/apps/index.html and create a pull request for it. Right, @michielbdejong?

**Comment by lduboeuf** [comment]
ah, i see ;-), thanks

**Comment by michielbdejong** [comment]
Yes! That's the idea :)
